[package]
name = "tls13tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
x25519-dalek = "2"
pretty_assertions = "1.4.0"
log = "0.4.21"
env_logger = "0.11.3"
